apiVersion: apps/v1
kind: Deployment
metadata:
  name: turtle-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: turtle
  template:
    metadata:
      labels:
        app: turtle
    spec: 
      containers:
      - name: nginx
        image: nginx:stable
